all : rapport

rapport :
		pdflatex rapport.tex>/dev/null  && pdflatex rapport.tex>/dev/null  

clean :
	rm -f ./*.aux
	rm -f ./*.log
	rm -f ./*.out
	rm -f ./*.pdf
	rm -f ./*.synctex.gz
	rm -f ./*.toc
